const { Client } = require("pg");
const express = require("express");
const path = require("path");
const axios = require("axios");
const FormData = require("form-data");
const jsonServer = require("json-server");
const sgMail = require("@sendgrid/mail");
const draftsRouter = require("./routes/drafts");

const app = express();
const router = jsonServer.router("db.json");
const middlewares = jsonServer.defaults();

app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));
app.use(draftsRouter);

// --------------------------------------------------
// Get Auth0 Management API Token
// --------------------------------------------------
async function getAuth0ManagementToken() {
  try {
    const response = await axios.post(
      `https://${process.env.AUTH0_DOMAIN}/oauth/token`,
      {
        client_id: process.env.AUTH0_CLIENT_ID,
        client_secret: process.env.AUTH0_CLIENT_SECRET,
        audience: `https://${process.env.AUTH0_DOMAIN}/api/v2/`,
        grant_type: "client_credentials"
      },
      {
        headers: {
          "Content-Type": "application/json"
        }
      }
    );

    return response.data.access_token;

  } catch (error) {
    console.error(
      "Auth0 token error:",
      error.response?.data || error.message
    );

    throw new Error(
      "Unable to obtain Auth0 Management API token"
    );
  }
}


// --------------------------------------------------
// Create Auth0 User + AEP Profile
// --------------------------------------------------
app.post("/api/users", async (req, res) => {
  try {

    const {
      email,
      password,
      firstName,
      lastName
    } = req.body;


    // ------------------------------------------------
    // Validate request
    // ------------------------------------------------
    if (!email || !password) {
      return res.status(400).json({
        success: false,
        error: "email and password are required"
      });
    }


    // =================================================
    // STEP 1: GET AUTH0 MANAGEMENT TOKEN
    // =================================================

    const accessToken = await getAuth0ManagementToken();


    // =================================================
    // STEP 2: CREATE USER IN AUTH0
    // =================================================

    const auth0Response = await axios.post(
      `https://${process.env.AUTH0_DOMAIN}/api/v2/users`,
      {
        connection: process.env.AUTH0_CONNECTION,

        email: email,

        password: password,

        given_name: firstName,

        family_name: lastName,

        email_verified: false
      },
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json"
        }
      }
    );


    // =================================================
    // STEP 3: GET USER ID GENERATED BY AUTH0
    // =================================================

    const auth0User = auth0Response.data;

    const auth0UserId = auth0User.user_id;

    console.log(
      "Auth0 user created:",
      auth0UserId
    );


    // =================================================
    // STEP 4: BUILD AEP PROFILE
    // =================================================

    const aepPayload = {

      _techmarketingdemos: {

        // Auth0-generated user_id becomes
        // the AEP primary identity

        crmid: auth0UserId,

        Email:
          auth0User.email || email,

        FirstName:
          auth0User.given_name || firstName || "",

        LastName:
          auth0User.family_name || lastName || ""
      }
    };


    console.log(
      "Sending AEP profile:",
      JSON.stringify(aepPayload)
    );


    // =================================================
    // STEP 5: SEND PROFILE TO AEP
    // =================================================

    const aepResponse = await axios.post(
      process.env.AEP_STREAMING_URL,

      aepPayload,

      {
        headers: {
          "Content-Type": "application/json",
           "x-adobe-flow-id": process.env.AEP_DATAFLOW_ID
        },

        timeout: 15000
      }
    );


    console.log(
      "AEP ingestion response:",
      aepResponse.data
    );


    // =================================================
    // STEP 6: RETURN RESULT
    // =================================================

    return res.status(201).json({

      success: true,

      user: {

        userId: auth0UserId,

        email:
          auth0User.email,

        firstName:
          auth0User.given_name,

        lastName:
          auth0User.family_name
      },

      aep: {

        success: true,

        inletId:
          aepResponse.data?.inletId || null,

        xactionId:
          aepResponse.data?.xactionId || null,

        receivedTimeMs:
          aepResponse.data?.receivedTimeMs || null
      }
    });


  } catch (error) {

    console.error(
      "User creation failed:",
      error.response?.data || error.message
    );

    return res
      .status(error.response?.status || 500)
      .json({

        success: false,

        error:
          error.response?.data?.message ||
          error.response?.data?.error_description ||
          error.response?.data ||
          error.message
      });
  }
});

async function getDraftForms() {
    const client = new Client({
        host: process.env.AEP_QUERY_HOST,
        port: Number(process.env.AEP_QUERY_PORT),
        database: process.env.AEP_QUERY_DATABASE,
        user: process.env.AEP_QUERY_USER,
        password: process.env.AEP_QUERY_PASSWORD,
        ssl: {
            rejectUnauthorized: false
        }
    });

    await client.connect();

    const result = await client.query(`
        SELECT
            _techmarketingdemos.formname,
            _techmarketingdemos.email,
            _techmarketingdemos.ownerid,
            _techmarketingdemos.savedat
        FROM
            formsportalstatus_v2_20260731_172643_669
        WHERE
            _techmarketingdemos.submitted = FALSE
            AND _techmarketingdemos.savedat IS NOT NULL
        ORDER BY
            _techmarketingdemos.savedat DESC
    `);

    await client.end();

    return result.rows;
}

const allowedOrigins = [
  "https://publish-p133654-e1305513.adobeaemcloud.com",
  "https://author-p133654-e1305513.adobeaemcloud.com"
];
app.use((req, res, next) => {
  const origin = req.headers.origin;

  if (allowedOrigins.includes(origin)) {
    res.setHeader("Access-Control-Allow-Origin", origin);
    res.setHeader("Vary", "Origin");
    res.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
    res.setHeader("Access-Control-Allow-Credentials", "true");
  }

  if (req.method === "OPTIONS") {
    return res.sendStatus(204);
  }

  next();
});


// Serve static files first
app.use(express.static(path.join(__dirname)));
app.get("/drafts", async (req, res) => {

    res.send(`
<!DOCTYPE html>
<html>
<head>

<title>Forms Saved As Draft</title>

<link rel="stylesheet"
href="https://unpkg.com/@spectrum-css/spectrum@3.1.0/dist/spectrum-core.css">

<style>

body{
    font-family:Arial;
    margin:40px;
    background:#f5f5f5;
}

.container{
    background:white;
    padding:30px;
    border-radius:8px;
}

table{
    width:100%;
    border-collapse:collapse;
    margin-top:20px;
}

th{
    text-align:left;
    background:#1473e6;
    color:white;
    padding:12px;
}

td{
    padding:10px;
    border-bottom:1px solid #ddd;
}

input{
    width:300px;
    padding:10px;
    font-size:15px;
}

</style>

</head>

<body>

<div class="container">

<h2>Forms Saved As Draft</h2>

<input
type="text"
id="search"
placeholder="Search by email or form name">

<table id="draftTable">

<thead>

<tr>
<th>Form Name</th>
<th>Email</th>
<th>Saved At</th>
</tr>

</thead>

<tbody>

</tbody>

</table>

</div>

<script>

async function loadDrafts(){

    const response = await fetch('/api/drafts');

    const drafts = await response.json();

    const tbody = document.querySelector("#draftTable tbody");

    tbody.innerHTML="";

    drafts.forEach(d=>{

        tbody.innerHTML += \`
        <tr>
            <td>\${d.formname}</td>
            <td>\${d.email}</td>
            <td>\${d.savedat}</td>
        </tr>
        \`;

    });

}

document.getElementById("search")
.addEventListener("keyup",function(){

    const value=this.value.toLowerCase();

    document
    .querySelectorAll("#draftTable tbody tr")
    .forEach(row=>{

        row.style.display=
        row.innerText.toLowerCase().includes(value)
        ? ""
        : "none";

    });

});

loadDrafts();

</script>

</body>

</html>
`);
});

app.get("/api/drafts", async (req, res) => {
    try {
        const drafts = await getDraftForms();
        res.json(drafts);
    } catch (err) {
        console.error(err);
        res.status(500).json({
            error: err.message
        });
    }
});
// Homepage
app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "index.html"));
});


app.get("/associate", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "associate-ui.html"));
});


// Your custom API routes here
// app.post('/generate-pdf-base64', ...)

// Mount json-server under /api only
const rewriter = jsonServer.rewriter(require("./routes.json"));
app.use("/api", middlewares);
app.use("/api", rewriter);
app.use("/api", router);

// Start server
const port = process.env.PORT || 10000;
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});

const AEP_API_BASE = 'https://platform.adobe.io';
const ACCESS_TOKEN = process.env.AEP_ACCESS_TOKEN;      // set this in .env
const API_KEY = process.env.AEP_API_KEY;                // x-api-key
const ORG_ID = process.env.AEP_ORG_ID;                  // x-gw-ims-org-id
const SANDBOX = process.env.AEP_SANDBOX || '';          // optional x-sandbox-name
const SENDGRID_API_KEY = process.env.SEND_GRID_API_KEY;

// --- CONFIG (env) ---
const AEM_COMM_BASE =
  'https://author-p133654-e1305513.adobeaemcloud.com/adobe/communications';
const AEM_COMM_URL =  'https://author-p133654-e1305513.adobeaemcloud.com/adobe/communications/f35ea2d9-6164-4791-8943-c56a6085eb91/pdf';
const AEM_BEARER = 'Basic Z2VlYmVlOmFkbWlu';                // e.g. "Bearer eyJ..."
//const INTERNAL_API_KEY = process.env.INTERNAL_API_KEY;    // Optional: simple protection

// SendGrid config (required for /generate-and-send)

const SENDGRID_FROM = 'newgeebee@outlook.com';         // verified sender e.g. "noreply@yourdomain.com"
if (SENDGRID_API_KEY) {
  sgMail.setApiKey(SENDGRID_API_KEY);
}

function buildHeaders() {
  const headers = {
    Authorization: `Bearer ${ACCESS_TOKEN}`,
    'x-api-key': API_KEY,
    'x-gw-ims-org-id': ORG_ID,
    'Content-Type': 'application/json'
  };
  if (SANDBOX) headers['x-sandbox-name'] = SANDBOX;
  return headers;
}
/**
 * GET /profile
 * Query params:
 *   ?email=someone@example.com     (look up by email identity namespace)
 *   OR
 *   ?xid=BVrq...                   (look up by profile XID)
 *
 * Example:
 *   GET /profile?email=joe%40example.com
 */
 app.get('/profile', async (req, res) => {
  try {
    const { email, xid } = req.query;

    if (!email && !xid) {
      return res.status(400).json({ error: 'Provide either ?email= or ?xid=' });
    }

    // fields can be adjusted to return exactly what you need
    const fields = [
      'personalEmail',
      '_techmarketingdemos.DocumentCloud',
      '_techmarketingdemos.ExperienceCloud',
      '_techmarketingdemos.ExperiencePlatform'
    ].join(',');

    let url = `${AEP_API_BASE}/data/core/ups/access/entities?schema.name=_xdm.context.profile&fields=${encodeURIComponent(fields)}`;

    if (xid) {
      url += `&entityId=${encodeURIComponent(xid)}`;
    } else {
      // assume email identity namespace
      url += `&entityId=${encodeURIComponent(email)}&entityIdNS=email`;
    }

    const response = await axios.get(url, { headers: buildHeaders() });

    // response data structure: { "<XID>": { entity: {...}, identities: [...], ... } }
    const data = response.data;
    const firstKey = Object.keys(data)[0];
    if (!firstKey || !data[firstKey].entity) {
      return res.status(404).json({ error: 'Entity not found' });
    }
    res.json(data[firstKey].entity);

  } catch (err) {
    console.error('Error fetching profile:', err.response ? err.response.data : err.message);
    const status = err.response ? err.response.status : 500;
    res.status(status).json({
      error: 'Unable to fetch profile',
      details: err.response ? err.response.data : err.message
    });
  }
});

// Simple health-check
app.get('/health', (req, res) => res.json({ status: 'ok' }));

/**
 * Helper: fetch PDF buffer from AEM Communications
 * returns: { buffer, status } or throws
 */
 async function fetchPdfBuffer(documentId, serviceParams = {}) {
  const url = `https://author-p133654-e1305513.adobeaemcloud.com/adobe/communications/${documentId}/pdf`;
  const optionsJson = JSON.stringify({
    prefill: {
      serviceName: 'IC_FDM',
      serviceParams: serviceParams || {}
    }
  });

  const form = new FormData();
  form.append('options', optionsJson, { contentType: 'application/json' });

  const resp = await axios.post(url, form, {
    headers: {
      ...form.getHeaders(),
      Authorization: AEM_BEARER
    },
    responseType: 'arraybuffer',
    validateStatus: null
  });

  if (resp.status < 200 || resp.status >= 300) {
    let bodyPreview = '';
    try {
      bodyPreview = Buffer.from(resp.data || '', 'binary').toString('utf8').slice(0, 400);
    } catch (e) {
      bodyPreview = '<non-text response>';
    }
    const err = new Error('communications service error');
    err.status = resp.status;
    err.bodyPreview = bodyPreview;
    throw err;
  }

  return Buffer.from(resp.data);
}
app.get("/getOrdersByUser/:userId", (req, res) => {
  const userId = Number(req.params.userId);
  const db = router.db; // lowdb instance
  const orders = db.get("orders").filter({ userId }).value();

  // Detect AEM: (1) explicit query flag ?_aem=1, (2) Accept header containing 'application/aem',
  // or (3) User-Agent containing 'AEM'. Adjust detection rules if needed.
  const accept = (req.headers["accept"] || "").toLowerCase();
  const ua = (req.headers["user-agent"] || "").toLowerCase();
  const isAem =
    req.query._aem === "1" ||
    accept.includes("application/aem") ||
    /aem/.test(ua);

  if (isAem) {
    // AEM-friendly: return raw array
    return res.json(orders);
  }

  // Default: backward-compatible wrapper
  return res.json({ orders });
});
app.get("/users/:userId/orders", (req, res) => {
  const userId = Number(req.params.userId);
  const db = router.db;
  const orders = db.get("orders").filter({ userId }).value();
  return res.json({ orders });
});

app.post("/submit", (req, res) => {
  console.log("Form submission received:");
  console.log(req.body);

  res.status(200).json({
    success: true,
    message: "Submission received"
  });
});
app.post('/send-pdf-email', async (req, res) => {
  try {
    if (!SENDGRID_API_KEY || !SENDGRID_FROM) {
      return res.status(500).json({
        error: 'SendGrid not configured. Set SENDGRID_API_KEY and SENDGRID_FROM env vars.'
      });
    }

    const {
      to,
      pdfBase64,
      subject,
      text,
      filename
    } = req.body;

    if (!to) {
      return res.status(400).json({ error: 'missing recipient email (to)' });
    }

    if (!pdfBase64) {
      return res.status(400).json({ error: 'missing pdfBase64' });
    }

    const msg = {
      to,
      from: SENDGRID_FROM,
      subject: subject || 'Your PDF document',
      text: text || 'Please find attached.',
      attachments: [
        {
          content: pdfBase64,
          type: 'application/pdf',
          filename: filename || 'document.pdf',
          disposition: 'attachment'
        }
      ]
    };

    const result = await sgMail.send(msg);

    return res.json({
      status: 'sent',
      sendgridResponse: Array.isArray(result)
        ? result[0].statusCode
        : result?.statusCode
    });
  } catch (error) {
    console.error(
      'email-pdf error',
      error.response ? (error.response.body || error.response) : error.message || error
    );

    const errBody =
      error.response &&
      (error.response.body || error.response.data)
        ? error.response.body || error.response.data
        : undefined;

    return res.status(500).json({
      error: 'Failed to send email',
      details: errBody || error.message
    });
  }
});
app.post("/generate-pdf", async (req, res) => {
  try {
    // Support either direct fields or nested under formData
    const body = req.body || {};
    const source = body.formData || body.payload || body;

    const documentId = source.documentId || body.documentId || req.query.documentId;
    const userId = source.userId || body.userId || req.query.userId;
    const entityNS = source.entityNS || body.entityNS;
    const entityID = source.entityID || body.entityID;

    if (!documentId) {
      return res.status(400).json({ error: "missing documentId" });
    }

    let serviceParams = {};

    if (entityNS && entityID) {
      serviceParams = { entityNS, entityID };
    } else if (userId) {
      serviceParams = { userId };
    } else {
      return res.status(400).json({
        error: "missing required parameters (userId OR entityNS/entityID)"
      });
    }

    const pdfBuffer = await fetchPdfBuffer(documentId, serviceParams);

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", 'inline; filename="generated.pdf"');
    return res.status(200).send(pdfBuffer);
  } catch (error) {
    if (error.status) {
      console.error("AEM error", error.status, error.bodyPreview);
      return res.status(502).json({
        error: "communications service error",
        status: error.status,
        bodyPreview: error.bodyPreview
      });
    }

    console.error("wrapper error", error.message || error);
    return res.status(500).json({ error: "Failed to generate PDF" });
  }
});

/**
 * POST /generate-pdf-base64
 * Body: { "userId": "12345" }
 * Headers: (if AEM_BEARER not set) Authorization: Bearer <AEM_TOKEN>
 */
app.post('/generate-pdf-base64', async (req, res) => {
  try {
    // optional internal auth
    const documentId = req.body.documentId || req.query.documentId;

    if (!documentId) {
      return res.status(400).json({ error: 'missing documentId' });
    }
    const { userId, entityNS, entityID } = req.body;
   
    const aemAuth = AEM_BEARER || req.header('Authorization');
    if (!aemAuth) return res.status(401).json({ error: 'missing AEM Authorization' });
    if (entityNS && entityID) {
      serviceParams = {
        entityNS,
        entityID
      };
    } else if (userId) {
      serviceParams = {
        userId
      };
    } else {
      return res.status(400).json({
        error: 'missing required parameters (userId OR entityNS/entityID)'
      });
    }

    const aemUrl = `${AEM_COMM_BASE}/${documentId}/pdf`;
    const pdfBuffer = await fetchPdfBuffer(documentId, serviceParams);



    //const pdfBuffer = await fetchPdfBuffer(userId, aemAuth);
    const base64 = pdfBuffer.toString('base64');
    return res.json({ pdfBase64: base64 });
  } catch (error) {
    if (error.status) {
      console.error('AEM error', error.status, error.bodyPreview);
      return res.status(502).json({ error: 'communications service error', status: error.status, bodyPreview: error.bodyPreview });
    }
    console.error('wrapper error', error.message || error);
    return res.status(500).json({ error: 'Failed to generate PDF' });
  }
});

app.post('/email-pdf', async (req, res) => {
  try {
    if (!SENDGRID_API_KEY || !SENDGRID_FROM) {
      return res.status(500).json({
        error: 'SendGrid not configured. Set SENDGRID_API_KEY and SENDGRID_FROM env vars.'
      });
    }

    const {
      documentId,
      userId,
      entityNS,
      entityID,
      to,
      subject,
      text,
      filename
    } = req.body;

    if (!documentId) {
      return res.status(400).json({ error: 'missing documentId' });
    }

    if (!to) {
      return res.status(400).json({ error: 'missing recipient email (to)' });
    }

    let serviceParams = {};

    if (entityNS && entityID) {
      serviceParams = { entityNS, entityID };
    } else if (userId) {
      serviceParams = { userId };
    } else {
      return res.status(400).json({
        error: 'missing required parameters (userId OR entityNS/entityID)'
      });
    }

    const aemAuth = AEM_BEARER || req.header('Authorization');
    if (!aemAuth) {
      return res.status(401).json({ error: 'missing AEM Authorization' });
    }

    const pdfBuffer = await fetchPdfBuffer(documentId, serviceParams);
    const pdfBase64 = pdfBuffer.toString('base64');

    const msg = {
      to,
      from: SENDGRID_FROM,
      subject: subject || 'Thank you for your interest in Adobe Cloud Solutions',
      text: text || 'Please find additional documentation on the solutions requested',
      attachments: [
        {
          content: pdfBase64,
          type: 'application/pdf',
          filename: filename || 'Adobe_Cloud_Solutions.pdf',
          disposition: 'attachment'
        }
      ]
    };

    const result = await sgMail.send(msg);

    return res.json({
      status: 'sent',
      sendgridResponse: Array.isArray(result)
        ? result[0].statusCode
        : (result && result.statusCode)
    });
  } catch (error) {
    if (error.status) {
      console.error('AEM error', error.status, error.bodyPreview);
      return res.status(502).json({
        error: 'communications service error',
        status: error.status,
        bodyPreview: error.bodyPreview
      });
    }

    console.error('email-pdf error', error.response ? (error.response.body || error.response) : error.message || error);

    const errBody =
      error.response &&
      (error.response.body || error.response.data)
        ? error.response.body || error.response.data
        : undefined;

    return res.status(500).json({
      error: 'Failed to send email',
      details: errBody || error.message
    });
  }
});


/**
 * POST /generate-and-send
 * Body (JSON):
 * {
 *   "userId": "12345",                // required: forwarded to FDM
 *   "to": "recipient@example.com",    // required
 *   "subject": "Your PDF",            // optional
 *   "text": "Please find attached.",  // optional plain text
 *   "filename": "document.pdf"        // optional filename for attachment
 * }
 *
 * Headers:
 * - If AEM_BEARER not set in env, include Authorization: Bearer <AEM_TOKEN>
 * - If INTERNAL_API_KEY is set, include x-api-key: <INTERNAL_API_KEY>
 *
 * Requires SENDGRID_API_KEY and SENDGRID_FROM to be set in env.
 */
app.post('/generate-and-send', async (req, res) => {
  try {
    // internal auth
    
    // Validate SendGrid config
    if (!SENDGRID_API_KEY || !SENDGRID_FROM) {
      return res.status(500).json({ error: 'SendGrid not configured. Set SENDGRID_API_KEY and SENDGRID_FROM env vars.' });
    }

    const { userId, to, subject, text, filename } = req.body;
    if (!userId) return res.status(400).json({ error: 'missing userId' });
    if (!to) return res.status(400).json({ error: 'missing recipient email (to)' });

    const aemAuth = AEM_BEARER || req.header('Authorization');
    if (!aemAuth) return res.status(401).json({ error: 'missing AEM Authorization' });

    // 1) generate PDF from AEM (buffer)
    const pdfBuffer = await fetchPdfBuffer(userId, aemAuth);

    // 2) base64 encode
    const pdfBase64 = pdfBuffer.toString('base64');

    // 3) send via SendGrid
    const msg = {
      to: to,
      from: SENDGRID_FROM,
      subject: subject || 'Your generated PDF',
      text: text || 'Please find attached.',
      attachments: [
        {
          content: pdfBase64,
          type: 'application/pdf',
          filename: filename || 'document.pdf',
          disposition: 'attachment'
        }
      ]
    };

    // Optional: include dynamic_template_id or html content if desired
    const result = await sgMail.send(msg); // returns array for multiple recipients sometimes
    // SendGrid returns 202 Accepted; not always returns body, but success if no error thrown
    return res.json({ status: 'sent', sendgridResponse: Array.isArray(result) ? result[0].statusCode : (result && result.statusCode) });
  } catch (error) {
    // handle AEM upstream error
    if (error.status) {
      console.error('AEM error', error.status, error.bodyPreview);
      return res.status(502).json({ error: 'communications service error', status: error.status, bodyPreview: error.bodyPreview });
    }
    // handle sendgrid / other errors
    console.error('generate-and-send error', error.response ? (error.response.body || error.response) : error.message || error);
    const errBody = error.response && (error.response.body || error.response.data) ? error.response.body || error.response.data : undefined;
    return res.status(500).json({ error: 'Failed to generate and send', details: errBody || error.message });
  }
});

